#include "main.h"

#include <stdio.h>
#include <stdlib.h>

#include "gba.h"
#include "images/garbage.h"
#include "images/titlescreen.h"
#include "images/lossscreen.h"
#include "images/winscreen.h"
#include "images/lightswitch.h"
/* TODO: */
// Include any header files for title screen or exit
// screen images generated by nin10kit. Example for the provided garbage
// image:
// #include "images/garbage.h"

/* TODO: */
// Add any additional states you need for your app. You are not requried to use
// these specific provided states.
enum gba_state {
  START,
  PLAY,
  WIN,
  LOSE,
};

int main(void) {
  /* TODO: */
  // Manipulate REG_DISPCNT here to set Mode 3. //
  REG_DISPCNT = MODE3 | BG2_ENABLE;
  // Save current and previous state of button input.
  u32 previousButtons = BUTTONS;
  u32 currentButtons = BUTTONS;

  // Load initial application state
  enum gba_state state = START;
  int first_start = 1;
  int first_draw = 1;
  int first_win = 1;
  int first_lose = 1;
  player.row = 10;
  player.col = 10;
  player.width = 5;
  player.height = 5;
  ls.row = randint(20, 160);
  ls.col = randint(20, 240);
  ls.width = LIGHTSWITCH_WIDTH;
  ls.height = LIGHTSWITCH_HEIGHT;
  unsigned int currVBlank = 0;
  unsigned int score = 100;
  char buffer[60];
  int win = 0;

  while (1) {
    currentButtons = BUTTONS; // Load the current state of the buttons
    
    
    /* TODO: */
    // Manipulate the state machine below as needed //
    // NOTE: Call waitForVBlank() before you draw

    switch (state) {
      case START:
      if (first_start) {
        waitForVBlank();
        drawFullScreenImageDMA(titlescreen);
        drawCenteredString(10, WIDTH / 2 - 18, 30, 10, "LIGHTS OUT", RED);
        drawCenteredString(10 + 3, WIDTH / 2 - 15, 30, 10, "LIGHTS OUT", RED);
        drawCenteredString(140, WIDTH / 2 - 18, 30, 10, "PRESS START TO PLAY", RED);
        first_start = 0;
      }
      

      if (KEY_DOWN(BUTTON_START, BUTTONS)) {
        state = PLAY;
        break;
      }
        
        // state = ?
        break;
      case PLAY:
        if (first_draw) {
          fillScreenDMA(BLACK);
          first_draw = 0;
          drawImageDMA(ls.row, ls.col, LIGHTSWITCH_WIDTH, LIGHTSWITCH_HEIGHT, lightswitch);
          for (int i = 0; i <= 200; i++) {
            waitForVBlank();
          }
          fillScreenDMA(BLACK);
          currVBlank = vBlankCounter;
          sprintf(buffer, "Score: %d", score);
          drawCenteredString(140, 120, 10, 10, buffer, RED);
        }
        int i = 1;
        while (vBlankCounter < currVBlank + 60 * 5) {
          if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
            state = START;
            first_draw = 1;
            first_lose = 1;
            first_start = 1;
            first_win = 1;
            player.row = 10;
            player.col = 10;
            score = 100;
            win = 0;
            ls.row = randint(20, 160);
            ls.col = randint(20, 240);
            break;
          }
          waitForVBlank();
          if (vBlankCounter > currVBlank + 30 * i) {
            score -= 10;
            i++;
            drawRectDMA(140, 80, 100, 10, BLACK);
            sprintf(buffer, "Score: %d", score);
            drawCenteredString(140, 120, 10, 10, buffer, RED);
          }
          if (KEY_DOWN(BUTTON_RIGHT, BUTTONS)) {
            drawRectDMA(player.row, player.col, player.width, player.height, BLACK);
            player.col++;
          }
          if (KEY_DOWN(BUTTON_LEFT, BUTTONS)) {
            drawRectDMA(player.row, player.col, player.width, player.height, BLACK);
            player.col--;
          }
          if (KEY_DOWN(BUTTON_UP, BUTTONS)) {
            drawRectDMA(player.row, player.col, player.width, player.height, BLACK);
            player.row--;
          }
          if (KEY_DOWN(BUTTON_DOWN, BUTTONS)) {
            drawRectDMA(player.row, player.col, player.width, player.height, BLACK);
            player.row++;
          }
          int col_in_range_left = (player.col + player.width) > ls.col && player.col < ls.col;
          int col_in_range_right = (player.col + player.width) > (ls.col + ls.width) && player.col < (ls.col + ls.width);
          int col_in_range = col_in_range_left || col_in_range_right;
          
          int row_in_range_top = (player.row + player.height) > ls.row && player.row < ls.row;
          int row_in_range_bottom = (player.row + player.height) > (ls.row + ls.height) && player.row < (ls.row + ls.height);
          int row_in_range = row_in_range_bottom || row_in_range_top;
          if (row_in_range && col_in_range) {
            state = WIN;
            win = 1;
            break;
          }
        drawRectDMA(player.row, player.col, player.width, player.height, BLUE);
        
        
      }
      if (state == START) {
          break;
        }
      if (!win) {
        state = LOSE;
      }
        
        // state = ?
        break;
      case WIN:
      if (first_win) {
        waitForVBlank();
        drawFullScreenImageDMA(winscreen);
        drawCenteredString(140, 120, 10, 10, buffer, WHITE);
        drawCenteredString(20, WIDTH / 2 - 18, 30, 10, "You won!", WHITE);
        first_win = 0;
      }
      if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
            state = START;
            first_draw = 1;
            first_lose = 1;
            first_start = 1;
            first_win = 1;
            player.row = 10;
            player.col = 10;
            score = 100;
            win = 0;
            ls.row = randint(20, 160);
            ls.col = randint(20, 240);
      }
        // state = ?
        break;
      case LOSE:
      if (first_lose) {
        waitForVBlank();
        drawFullScreenImageDMA(lossscreen);
        drawCenteredString(140, WIDTH / 2 - 18, 30, 10, "You Lost.", RED);
        first_lose = 0;
      }
        if (KEY_DOWN(BUTTON_SELECT, BUTTONS)) {
            state = START;
            first_draw = 1;
            first_lose = 1;
            first_start = 1;
            first_win = 1;
            player.row = 10;
            player.col = 10;
            score = 100;
            win = 0;
            ls.row = randint(20, 160);
            ls.col = randint(20, 240);
          }
        // state = ?
        break;
    }

    previousButtons = currentButtons; // Store the current state of the buttons
  }

  UNUSED(previousButtons); // You can remove this once previousButtons is used

  return 0;
}
